
name: Selenium Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies (Python + Node)
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytest webdriver-manager
        npm install

    - name: Start web server
      run: |
        nohup npm run dev &
        sleep 5

    - name: Run tests
      run: pytest autotests
